on:
  pull_request:
  push:
    branches:
      - main
      
      
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: action/setup-python@v4
        with: 
         python-version: "3.11"
        
      - name: intsall package and test requirements
        run: python -m pip install .[test]
      
      - run: python -m pytest
        
